### ISSUE TITLE
Have a look at multi stage builds

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/docker#164]
https://docs.docker.com/develop/develop-images/multistage-build/

Could be of use for the scafacos build.

**Comment by mkuron** [comment]
They are mainly useful if you want to build library A with base image B and application C with base image D, while copying the library A binaries over into the final image.

Since Scafacos needs to be built on the same compiler etc. as Espresso later, we wouldn't gain anything by splitting into two stages.
