### ISSUE TITLE
same ccache version in all containers?

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/docker#38]
It seems that the different ccache versions don't play well together, the output for the cache size varies with the ccache version.

**Comment by mkuron** [comment]
The better solution would be to use different cache directories for each Docker image. However, I don't think that it's even necessary: ccache includes the compiler version in its hashes and there is no database or anything that could be version-specific in the cache directory.

**Comment by mkuron** [comment]
https://github.com/ccache/ccache/issues/194 maybe?

**Comment by mkuron** [comment]
Oh, you can't do stats on a shared cache. Please revert https://github.com/espressomd/espresso/pull/2260. You need to do `ccache -z` at the beginning of your build to clear the stats and `ccache -s` at the end to view them. Since the stats are stored _$CCACHE_DIR/[0-9a-f]/stats_, they are shared, making them useless.

**Comment by KaiSzuttor** [comment]
can you explain why they are useless?

**Comment by mkuron** [comment]
If two jobs run simultaneously on the same cache, they both reset and update the statistics. So the hit and miss rates you get are the combined rate of both jobs.

**Comment by KaiSzuttor** [comment]
but what if i reset before build and another job resets during my build, isn’t the stat then always useless?

**Comment by mkuron** [comment]
Precisely
